CREATE TABLE
    client (
        -- user-designated client ID
        client_id VARCHAR PRIMARY KEY
    );

CREATE TABLE
    "character" (
        -- the UUID generated by the UI
        uuid UUID PRIMARY KEY NOT NULL,
        -- the sequential ID in the UI's sqlite database
        remote_id INTEGER NOT NULL,
        "url" VARCHAR,
        payload JSONB NOT NULL,
        client_id VARCHAR NOT NULL REFERENCES client (client_id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    chat (
        -- the UUID generated by the UI
        uuid UUID PRIMARY KEY NOT NULL,
        -- the sequential ID in the UI's sqlite database
        remote_id INTEGER NOT NULL,
        title VARCHAR,
        character_id UUID NOT NULL REFERENCES "character" (uuid),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        payload JSONB NOT NULL,
        archived BOOLEAN NOT NULL DEFAULT false,
        client_id VARCHAR NOT NULL REFERENCES client (client_id)
    );